version: '3'
services:
  netcat: &netcat
    build: ./netcat_server
    networks:
      - backend
    expose: 
      - "8080"
    environment:
      - VIRTUAL_HOST=hello.world.local  
    healthcheck:
      test: ["CMD", "true"]


  netcat_server_blue:
    <<: *netcat

  netcat_server_green:
    <<: *netcat

  nginx:
    image: jwilder/nginx-proxy:alpine
    expose:
      - "80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - frontend
      - backend

  curl_client:
    build: ./curl_client
    depends_on:
      - nginx
    networks:
      - frontend
networks:
  frontend:
  backend:
